TELEGRAM_TOKEN = "7717518645:AAEgUmtn3b3Fjb8b82dFII3PnmiKzbNjm7I"
GEMINI_API_KEY = "AIzaSyDnfKIHsBzEzUyT4AIPfwW2Ulv0uPbEXgw"
SUPABASE_URL = "https://pqixlbgoecrjnhizqpld.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxaXhsYmdvZWNyam5oaXpxcGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NjYyODEsImV4cCI6MjA1NjM0MjI4MX0.PA80laWyX3_VLMho_84p--plPoCEuac_yk8FsmOgNfU"
SUPPORTED_LANGUAGES = ["en", "hi", "te"]
LOG_FILE = "bot_v12.log"
